services:

  tuvendedor_wa:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: tuvendedor_wa

    env_file:
      - .env.production

    environment:
      NODE_ENV: production

    volumes:

      # SESIÓN DE WHATSAPP
      - /srv/tuvendedor/whatsapp/auth:/app/.wwebjs_auth

      # CACHE
      - /srv/tuvendedor/whatsapp/cache:/app/.wwebjs_cache

    ports:
      - "127.0.0.1:3100:3100"

    networks:
      - ecommerce_network

    restart: unless-stopped

    init: true

    shm_size: "512mb"


networks:

  ecommerce_network:

    external: true

    name: ecommerce_network